# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "All Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "How To"
  parent = "Categories"
  pageRef = "categories/how-to"
  weight = 22

[[main]]
  name = "Life"
  parent = "Categories"
  pageRef = "categories/life"
  weight = 23

[[main]]
  name = "Long Form Responses"
  parent = "Categories"
  pageRef = "categories/lfr"
  weight = 24

[[main]]
  name = "Presentations"
  parent = "Categories"
  pageRef = "categories/presentations"
  weight = 24

[[main]]
  name = "Standards Work"
  url = "/standards-work"
  weight = 70

[[main]]
  name = "Photos"
  url = "https://photos.timcappalli.me"
  weight = 90

#[[main]]
# identifier = "About"
# pre = "circle-info"
# weight = 200
# url = "https://timcappalli.me"
#
#
#[[main]]
# identifier = "bluesky"
# pre = "bluesky"
# weight = 300
# url = "https://bsky.app/profile/timcappalli.me"
#
#[[main]]
# identifier = "mastodon"
# pre = "mastodon"
# weight = 400
# url = "https://infosec.exchange/@timcappalli"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
